# Generated by Django 5.2.7 on 2026-05-28 02:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestStrategy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('strategy_type', models.CharField(choices=[('SMA_CROSSOVER', 'SMA Crossover'), ('EMA_CROSSOVER', 'EMA Crossover'), ('RSI', 'RSI Strategy'), ('MACD', 'MACD Strategy'), ('BOLLINGER_BANDS', 'Bollinger Bands')], max_length=50)),
                ('param_fast_period', models.IntegerField(default=10)),
                ('param_slow_period', models.IntegerField(default=30)),
                ('param_signal_period', models.IntegerField(default=9)),
                ('param_rsi_period', models.IntegerField(default=14)),
                ('param_rsi_overbought', models.IntegerField(default=70)),
                ('param_rsi_oversold', models.IntegerField(default=30)),
                ('param_bb_period', models.IntegerField(default=20)),
                ('param_bb_std', models.FloatField(default=2.0)),
                ('initial_capital', models.DecimalField(decimal_places=2, default=100000, max_digits=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('total_return_pct', models.FloatField(default=0.0)),
                ('total_profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('max_drawdown_pct', models.FloatField(default=0.0)),
                ('sharpe_ratio', models.FloatField(default=0.0)),
                ('initial_capital', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('final_capital', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('best_trade_pct', models.FloatField(default=0.0)),
                ('worst_trade_pct', models.FloatField(default=0.0)),
                ('avg_trade_pct', models.FloatField(default=0.0)),
                ('equity_curve_json', models.TextField(default='[]')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='app.backteststrategy')),
            ],
        ),
        migrations.CreateModel(
            name='BacktestTrade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trade_type', models.CharField(default='BUY->SELL', max_length=20)),
                ('entry_date', models.CharField(max_length=50)),
                ('exit_date', models.CharField(blank=True, max_length=50)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('profit_loss_pct', models.FloatField(blank=True, null=True)),
                ('signal', models.CharField(blank=True, max_length=100)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='app.backtestresult')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('symbol_id', models.CharField(blank=True, max_length=255)),
                ('dhan_security_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='LivePrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=50)),
                ('symbol_id', models.CharField(blank=True, max_length=255)),
                ('live_price', models.CharField(max_length=50)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='app.stock')),
            ],
        ),
        migrations.AddField(
            model_name='backteststrategy',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stock'),
        ),
        migrations.CreateModel(
            name='TradeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stock')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
