# Generated by Django 5.2.7 on 2026-05-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='security_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
